<?php
$form->prepare();
$escapeHtml = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/exportc.css', 'Export'));
$this->headScript()->appendFile($this->assetUrl('js/export.js', 'Export'));
?>

<?php echo $this->pageTitle($this->translate('Metadata Editor'), 1, $this->translate('Metadata Editor')); ?>

<?php echo $this->form()->openTag($form); ?>

<?php echo $this->formCollection($form, false); ?>

<?php echo $this->form()->closeTag($form); ?>
