<h1>Find & Replace Preview</h1>
<p>Replace <b><?= $find  ?></b> with <b><?= $replace ?></b> in property <b><?= $property ?>:<?= $propertyName ?></b>.</p> 
<p>Found <b><?= $count  ?></b> matching items.</p> 


<?php 
$results = json_encode($collection);
$action = str_replace("preview", "replace", $this->serverUrl(true));
?>
<form action="<?php echo $action; ?>" method="post">
<input type="hidden" name="find" value="<?php echo $find ?>"/>
<input type="hidden" name="replace" value="<?php echo $replace ?>"/>
<input type="hidden" name="property" value="<?php echo $property ?>"/>
<input type="hidden" name="propertyName" value="<?php echo $propertyName ?>"/>
<fieldset id='page-actions'>
    <button type="submit"><?php echo $this->translate('Replace'); ?></button>
</fieldset>
</form>

<?php 

foreach($collection as $item){
	echo $item['o:id'];
	echo "<br/>";
	echo $item['found'];
	echo "<br/>";
	echo $item['replace'];
	echo "<br/><br/>";
}

?>
